name: Detect Network Latency Experiment

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  detect-network-latency:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Detect Network Latency Issues
        run: python scripts/detect_network_latency_issues.py
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOUDWATCH_ALARM_NAME: ${{ secrets.CLOUDWATCH_ALARM_NAME }}
